# Setup
title: Juan D. Carvajal-Castro
description: Ph.D Student at SJU. (Santos lab)
url: 
#avatar: /Photos/cover.jpeg
paginate: 5
permalink: pretty
cover_image: /Photos/background.jpeg


google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

